### ISSUE TITLE
Can't edit RA properties through slee console

### ISSUE THREAD

**Issue by duyanh030** [RestComm/jain-slee#126] opened 2018-01-29 10:16 UTC
I get error  below when trying to update "gov.nist.javax.sip.TRACE_LEVEL :: java.lang.String" property

17:11:53:875 [ERROR] the property javax.sip.TRANSPORT has null value
Check the JAIN SLEE logs for more detailed information about this error.

![sipraedit](https://user-images.githubusercontent.com/26052474/35505234-0c2fbfe4-0518-11e8-972f-c209d36c499a.png)

**Comment by gsaslis** [comment] 2018-02-06 09:33
Thanks for raising the issue @duyanh030 !

can you please share some more information about the circumstances in which this error message comes up?

It would be really helpful if you could provide:
* steps to reproduce and 
* some more complete logs (using [GitHubGist](https://gist.github.com/) ), so we can take a closer look.

Thanks in advance!
Yorgos

**Comment by satanatoly** [comment] 2018-02-09 14:13
Thank you for reporting the issue @duyanh030
This bug was present in commercial version of JAIN SLEE. Fix was applied and will be included in 7.2.0 release

**Comment by gsaslis** [comment] 2018-02-09 14:43
@satanatoly if the bug was for a commercial version, then that would make this issue invalid?

@duyanh030 can you confirm, so we can proceed to close this one?

**Comment by satanatoly** [comment] 2018-02-19 13:05
@gsaslis nope, since the issue was already resolved that would make the issue solved.

**Comment by gsaslis** [comment] 2018-02-23 00:11
@satanatoly tbh, i am not sure i understood exactly what you mean... 
it sounds like we should now close this issue then?

**Comment by satanatoly** [comment] 2018-04-30 15:40
Resolved in [7.2.0](https://github.com/RestComm/jain-slee/releases?after=7.2.0-129.141) release. Closing

**Closed by satanatoly** 2018-04-30 15:40 UTC
